# Generated by Django 4.2.7 on 2023-11-08 04:28

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
from django.contrib.auth import get_user_model


User = get_user_model()
class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pregunta',
            old_name='text',
            new_name='question_text',
        ),
        migrations.RemoveField(
            model_name='pregunta',
            name='order',
        ),
        migrations.RemoveField(
            model_name='pregunta',
            name='reward_points',
        ),
        migrations.RemoveField(
            model_name='pregunta',
            name='survey',
        ),
        migrations.AddField(
            model_name='comentario',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comentario',
            name='delete_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comentario',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='comentario',
            name='deleted_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='comentario',
            name='parent_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.comentario'),
        ),
        migrations.AddField(
            model_name='encuesta',
            name='delete_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='encuesta',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='encuesta',
            name='deleted_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='delete_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='deleted_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='pregunta',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pregunta',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),

        migrations.AddField(
            model_name='pregunta',
            name='delete_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pregunta',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pregunta',
            name='deleted_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='pregunta',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='pregunta',
            name='status',
            field=models.CharField(choices=[('Dr', 'Borrador'), ('PB', 'Publicada'), ('CL', 'Cerrada')], default=datetime.datetime(2023, 11, 8, 4, 28, 11, 992842, tzinfo=datetime.timezone.utc), max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pregunta',
            name='title',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(auto_now=True, null=True)),
                ('delete_reason', models.TextField(blank=True, null=True)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.pregunta')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Alternativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(auto_now=True, null=True)),
                ('delete_reason', models.TextField(blank=True, null=True)),
                ('text', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('votes', models.IntegerField(default=0)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.encuesta')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='reporte',
            name='answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.alternativa'),
        ),
        migrations.AlterField(
            model_name='voto',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.alternativa'),
        ),
        migrations.DeleteModel(
            name='RespuestaSeleccion',
        ),
    ]
