# Generated by Django 4.2.7 on 2023-11-08 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_text_pregunta_question_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentario',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='alternativa',
            name='deleted_at',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='deleted_at',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='deleted_at',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='deleted_at',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='deleted_at',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='respuesta',
            name='deleted_at',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
